import type { NewsItem } from "../types/news"

export const mockNewsItems: NewsItem[] = [
  {
    slug: "article-1",
    title: "記事1のタイトル",
    excerpt: "記事1の概要です",
    date: "2025-01-06",
    category: "イベント",
    image: "/images/article1.jpg",
    author: "編集部",
    content: "記事1の本文",
    tags: ["イベント", "戸塚"],
  },
  {
    slug: "article-2",
    title: "記事2のタイトル",
    excerpt: "記事2の概要です",
    date: "2025-01-05",
    category: "生活",
    image: "/images/article2.jpg",
    author: "編集部",
    content: "記事2の本文",
    tags: ["生活", "情報"],
  },
  {
    slug: "article-3",
    title: "記事3のタイトル",
    excerpt: "記事3の概要です",
    date: "2025-01-04",
    category: "イベント",
    image: "/images/article3.jpg",
    author: "編集部",
    content: "記事3の本文",
    tags: ["イベント"],
  },
  {
    slug: "article-4",
    title: "記事4のタイトル",
    excerpt: "記事4の概要です",
    date: "2025-01-03",
    category: "子育て",
    image: "/images/article4.jpg",
    author: "編集部",
    content: "記事4の本文",
    tags: ["子育て"],
  },
]
