collections:
  - name: news
    label: ニュース
    folder: "src/content/news"
    format: "frontmatter"
    create: true
    slug: "{{year}}{{month}}{{day}}-{{fields.title | slugify}}"
    slug_encoding: ascii
    fields:
      - { name: title,   label: タイトル }
      - { name: excerpt, label: 抜粋, widget: text }
      - { name: date,    label: 公開日, widget: datetime }
      - { name: category,label: カテゴリ }
      - { name: image,   label: アイキャッチ, widget: image }
      - { name: author,  label: 編集者, required: false }
      - { name: tags,    label: タグ, widget: list, required: false }
      - name: related
        label: 関連記事
        widget: list
        required: false
      - { name: body,    label: 本文, widget: markdown }
